/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'relationship' : null } |
  { 'mentalHealth' : null } |
  { 'studies' : null } |
  { 'career' : null };
export interface ChatMessage {
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'category' : Category,
}
export interface Comment {
  'content' : string,
  'author' : Principal,
  'likes' : bigint,
}
export interface MoodEntry { 'timestamp' : bigint, 'rating' : bigint }
export interface Post {
  'title' : string,
  'content' : string,
  'author' : Principal,
  'likes' : bigint,
  'category' : Category,
  'comments' : Array<Comment>,
}
export interface PrivateMessage {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface Profile {
  'nickname' : string,
  'badges' : Array<string>,
  'isMentor' : boolean,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[Category, string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'addMoodEntry' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[Category, string, string], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[Category], Array<ChatMessage>>,
  'getMoodEntries' : ActorMethod<[Principal], Array<MoodEntry>>,
  'getPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'getPrivateMessages' : ActorMethod<
    [Principal, Principal],
    Array<PrivateMessage>
  >,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'saveProfile' : ActorMethod<[string], undefined>,
  'sendPrivateMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];