/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'relationship' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'studies' : IDL.Null,
  'career' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
});
export const Post = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'category' : Category,
  'comments' : IDL.Vec(Comment),
});
export const Profile = IDL.Record({
  'nickname' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'isMentor' : IDL.Bool,
  'points' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'category' : Category,
});
export const MoodEntry = IDL.Record({
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const PrivateMessage = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([Category, IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addMoodEntry' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([Category, IDL.Text, IDL.Text], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([Category], [IDL.Vec(ChatMessage)], ['query']),
  'getMoodEntries' : IDL.Func([IDL.Principal], [IDL.Vec(MoodEntry)], ['query']),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getPrivateMessages' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'saveProfile' : IDL.Func([IDL.Text], [], []),
  'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'relationship' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'studies' : IDL.Null,
    'career' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
  });
  const Post = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'category' : Category,
    'comments' : IDL.Vec(Comment),
  });
  const Profile = IDL.Record({
    'nickname' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'isMentor' : IDL.Bool,
    'points' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'category' : Category,
  });
  const MoodEntry = IDL.Record({ 'timestamp' : IDL.Int, 'rating' : IDL.Nat });
  const PrivateMessage = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([Category, IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addMoodEntry' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([Category, IDL.Text, IDL.Text], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([Category], [IDL.Vec(ChatMessage)], ['query']),
    'getMoodEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'getPrivateMessages' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'saveProfile' : IDL.Func([IDL.Text], [], []),
    'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };